# Generated by Django 4.1 on 2022-09-03 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0011_post_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="followers",
            field=models.ManyToManyField(
                related_name="blog_followers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
