# Generated by Django 4.1 on 2022-09-11 23:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0012_post_followers"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="like_count",
            field=models.BigIntegerField(default="0"),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(default="questions", max_length=255),
        ),
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="like",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
